#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

PIWIK_VERSION="3.5.1"
DESTDIR="/var/www/htdocs/piwik"

MUNIN_PLUGINS="
	apache_accesses
	apache_processes
	apache_volume
	httpd_memory
"

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Setup matomo"
mkdir -p $DESTDIR/releases

cd $DESTDIR/releases
curl -L -O https://download.qutic.com/src/piwik/matomo-$PIWIK_VERSION.tar.bz2
tar xf matomo-$PIWIK_VERSION.tar.bz2
rm matomo-$PIWIK_VERSION.tar.bz2
mv matomo matomo-$PIWIK_VERSION

cd $DESTDIR
ln -nfs $DESTDIR/releases/piwik-$PIWIK_VERSION current

touch $DESTDIR/releases/piwik-$PIWIK_VERSION/config/config.ini.php
chmod 0640 $DESTDIR/releases/piwik-$PIWIK_VERSION/config/config.ini.php

chown -R root:www "${DESTDIR}"
chown -R www:www "${DESTDIR}/current/tmp"
chmod 0777 "${DESTDIR}/current/tmp"
chmod 0777 "${DESTDIR}/current/tmp/cache/tracker"

# let plugins extend piwik.js
chmod +w "${DESTDIR}/current/piwik.js"
chown www:www "${DESTDIR}/current/piwik.js"

touch "${DESTDIR}/piwik-update.log"
chown www:www  "${DESTDIR}/piwik-update.log"

rm "${DESTDIR}/current/robots.txt"
cat >> "${DESTDIR}/current/robots.txt" << EOF
User-agent: *
Disallow: /
EOF

cd "${DESTDIR}/current/misc"
curl -L -O https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
gtar xf GeoLite2-City.tar.gz
mv GeoLite2-City_*/GeoLite2-City.mmdb .
rm GeoLite2-City.tar.gz
rm -rf GeoLite2-City_*

echo "* Change www for cronjobs"
usermod -d "$DESTDIR" -s /usr/bin/bash www

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Build libmaxminddb"
mkdir -p /opt/local/src
cd /opt/local/src
curl -L -O https://github.com/maxmind/libmaxminddb/releases/download/1.3.2/libmaxminddb-1.3.2.tar.gz
tar xf libmaxminddb-1.3.2.tar.gz 
cd libmaxminddb-1.3.2
./configure --prefix=/opt/local
gmake
gmake install

echo "* Build maxminddb"
cd /opt/local/src
curl -L -O https://github.com/maxmind/MaxMind-DB-Reader-php/archive/v1.3.0.tar.gz
gtar xf v1.3.0.tar.gz
cd MaxMind-DB-Reader-php-1.3.0/ext
./configure --prefix=/opt/local
gmake
gmake install

#
ln -nfs /opt/local/heirloom/bin/whoami /opt/local/bin/whoami

# Clean up
echo "* Cleaning up."
pkgin -y rm gcc49 gmake pkg-config autoconf
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
