#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

PIWIK_VERSION="2.17.1"
DESTDIR="/var/www/htdocs/piwik"

MUNIN_PLUGINS="
	apache_accesses
	apache_processes
	apache_volume
"

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Setup nextcloud"
mkdir -p $DESTDIR/releases

cd $DESTDIR/releases
curl -L -O https://download.qutic.com/src/piwik/piwik-$PIWIK_VERSION.tar.bz2
tar xf piwik-$PIWIK_VERSION.tar.bz2
rm piwik-$PIWIK_VERSION.tar.bz2
mv piwik piwik-$PIWIK_VERSION

cd $DESTDIR
ln -nfs $DESTDIR/releases/piwik-$PIWIK_VERSION current

chown -R root:root "${DESTDIR}"
chown -R www:www "${DESTDIR}/current/tmp"
chmod 0777 "${DESTDIR}/current/tmp"
chmod 0777 "${DESTDIR}/current/tmp/cache/tracker"

# let plugins extend piwik.js
chmod +w "${DESTDIR}/current/piwik.js"
chown www:www "${DESTDIR}/current/piwik.js"

touch "${DESTDIR}/piwik-update.log"
chown www:www  "${DESTDIR}/piwik-update.log"

rm "${DESTDIR}/current/robots.txt"
cat >> "${DESTDIR}/current/robots.txt" << EOF
User-agent: *
Disallow: /
EOF

echo "* Change www for cronjobs"
usermod -d "$DESTDIR" -s /usr/bin/bash www

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

# Clean up
echo "* Cleaning up."
rm /root/customize

# Prepare image for provisioning
sm-prepare-image -y
